# Generated by Django 5.2.6 on 2025-10-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cetegory',
            new_name='Category',
        ),
    ]
