# Generated by Django 5.2.6 on 2025-10-18 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_cetegory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category'),
        ),
    ]
